### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by rgooler** [Sonaza/Buffy#3]
Getting a ton of these - looks like some prereq or another got missed?

> 889x Buffy\core.lua:1430: <unnamed>:SetFormattedText(): Font not set
> [C]: in function `SetFormattedText'
> Buffy\core.lua:1430: in function `ShowBuffyAlert'
> Buffy\core.lua:1275: in function `UpdateBuffs'
> Buffy\core.lua:203: in function <Buffy\core.lua:175>
> (tail call): ?
> [C]: ?
> [string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
> (tail call): ?
> ...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
> ...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
> [C]: ?
> [C]: in function `LoadAddOn'
> FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
> FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
> FrameXML\UIParent.lua:995: in function <FrameXML\UIParent.lua:891>
> 
> Locals:
> nil

**Comment by rgooler** [comment]
As a note, using Buffy-2.1.0 from curse

**Comment by Sonaza** [comment]
Strange, I already fixed similar bug before but then it was caused by legitimately incorrect font path.

Recheck that you have the font file Interface\AddOns\Buffy\Media\DORISPP.TTF. It should be included in the zip archive.

**Comment by rgooler** [comment]
That is one missing file.

<img width="673" alt="2016-09-08 02_12_26-media" src="https://cloud.githubusercontent.com/assets/1108200/18343826/d3ea5552-7569-11e6-9f75-fa040d293dfe.png">

**Comment by Sonaza** [comment]
Try reinstalling the addon. I checked the file on Curse and it contains it so it should work after that.
